server:
  servlet:
    context-path: /reservo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservo
    username: reservo
    password: reservo
  jpa:
    hibernate:
      ddl-auto: update