spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservo
    username: reservo
    password: reservo
  jpa:
    hibernate:
      ddl-auto: create-drop
#security
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    root: info
